import Head from "next/head";
import Image from "next/image";
import logo from "../../../public/logoconecta.png";

const Conecta = () => {
  return (
    <>
      <Head>
        <title>Privacy Policy - Conecta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="wrapper my-4">
        <Image src={logo} alt="Logo Conecta" width={200} height={50} priority />

        <h1 className="font-bold py-4 text-2xl text-center my-10">
          Privacy Policy
        </h1>
        <p>
          Conecta built the Conecta app as a Commercial app. This SERVICE is
          provided by Conecta and is intended for use as is.
        </p>
        <p>
          This page is used to inform visitors regarding our policies with the
          collection, use, and disclosure of Personal Information if anyone
          decided to use our Service.
        </p>
        <p>
          If you choose to use our Service, then you agree to the collection and
          use of information in relation to this policy. The Personal
          Information that we collect is used for providing and improving the
          Service. We will not use or share your information with anyone except
          as described in this Privacy Policy.
        </p>
        <p>
          The terms used in this Privacy Policy have the same meanings as in our
          Terms and Conditions, which are accessible at Conecta unless otherwise
          defined in this Privacy Policy.
        </p>
        <h2 className="font-bold py-4">Information Collection and Use</h2>
        <p>
          For a better experience, while using our Service, we may require you
          to provide us with certain personally identifiable information,
          including but not limited to Name, Addresses, Phone numbers,Personal
          identification number, Personal features, Date of birth, Geographical
          location, Location data, Images, Camera. The information that we
          request will be retained by us and used as described in this privacy
          policy.
        </p>
        <div>
          <p>
            The app does use third-party services that may collect information
            used to identify you.
          </p>
          <p>
            Link to the privacy policy of third-party service providers used by
            the app
          </p>

          <div className="ml-10 mt-2">
            <ul className="list-disc">
              <li>
                <a
                  href="https://expo.io/privacy"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Expo
                </a>
              </li>
            </ul>
          </div>
        </div>
        <h2 className="font-bold py-4">Log Data</h2>
        <p>
          We want to inform you that whenever you use our Service, in a case of
          an error in the app we collect data and information (through
          third-party products) on your phone called Log Data. This Log Data may
          include information such as your device Internet Protocol (“IP”)
          address, device name, operating system version, the configuration of
          the app when utilizing our Service, the time and date of your use of
          the Service, and other statistics.
        </p>

        <h2 className="font-bold py-4">Cookies</h2>

        <p>
          Cookies are files with a small amount of data that are commonly used
          as anonymous unique identifiers. These are sent to your browser from
          the websites that you visit and are stored on your devices internal
          memory.
        </p>
        <p>
          This Service does not use these “cookies” explicitly. However, the app
          may use third-party code and libraries that use “cookies” to collect
          information and improve their services. You have the option to either
          accept or refuse these cookies and know when a cookie is being sent to
          your device. If you choose to refuse our cookies, you may not be able
          to use some portions of this Service.
        </p>

        <h2 className="font-bold py-4">Service Providers</h2>

        <p>
          We may employ third-party companies and individuals due to the
          following reasons:
        </p>
        <div className="ml-10 mb-4 mt-2">
          <ul className="list-disc">
            <li>To facilitate our Service;</li>
            <li>To provide the Service on our behalf;</li>
            <li>To perform Service-related services; or</li>
            <li>To assist us in analyzing how our Service is used.</li>
          </ul>
        </div>
        <p>
          We want to inform users of this Service that these third parties have
          access to their Personal Information. The reason is to perform the
          tasks assigned to them on our behalf. However, they are obligated not
          to disclose or use the information for any other purpose.
        </p>

        <h2 className="font-bold py-4">Security</h2>

        <p>
          We value your trust in providing us your Personal Information, thus we
          are striving to use commercially acceptable means of protecting it.
          But remember that no method of transmission over the internet, or
          method of electronic storage is 100% secure and reliable, and we
          cannot guarantee its absolute security.
        </p>
        <h2 className="font-bold py-4">Links to Other Sites</h2>
        <p>
          This Service may contain links to other sites. If you click on a
          third-party link, you will be directed to that site. Note that these
          external sites are not operated by us. Therefore, we strongly advise
          you to review the Privacy Policy of these websites. We have no control
          over and assume no responsibility for the content, privacy policies,
          or practices of any third-party sites or services.
        </p>

        <h2 className="font-bold py-4">Children’s Privacy</h2>

        <div>
          <p>
            These Services do not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from children
            under 13 years of age. In the case we discover that a child under 13
            has provided us with personal information, we immediately delete
            this from our servers. If you are a parent or guardian and you are
            aware that your child has provided us with personal information,
            please contact us so that we will be able to do the necessary
            actions.
          </p>
        </div>
        <h2 className="font-bold py-4">Changes to This Privacy Policy</h2>
        <p>
          We may update our Privacy Policy from time to time. Thus, you are
          advised to review this page periodically for any changes. We will
          notify you of any changes by posting the new Privacy Policy on this
          page.
        </p>
        <p>This policy is effective as of 2023-04-04</p>

        <h2 className="font-bold py-4">Contact Us</h2>

        <p>
          If you have any questions or suggestions about our Privacy Policy, do
          not hesitate to contact us at conectamobileapp@gmail.com.
        </p>
        <p>
          This privacy policy page was created at
          <a
            href="https://privacypolicytemplate.net"
            target="_blank"
            rel="noopener noreferrer"
          >
            privacypolicytemplate.net
          </a>
          and modified/generated by
          <a
            href="https://app-privacy-policy-generator.nisrulz.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            App Privacy Policy Generator
          </a>
        </p>

        <h1 className="font-bold py-4 text-2xl text-center my-10">
          Política de Privacidade
        </h1>
        <p>
          Conecta construiu a aplicação Conecta como uma aplicação comercial.
          Este SERVIÇO é fornecida pela Conecta e destina-se a ser utilizada tal
          como está.
        </p>
        <p>
          Esta página é utilizada para informar os visitantes sobre as nossas
          políticas com o recolha, utilização e divulgação de Informação
          Pessoal, se alguém decidiu utilizar o nosso Serviço.
        </p>
        <p>
          Se optar por utilizar o nosso Serviço, então concorda com a recolha e
          utilização da informação em relação a esta política. A Informação
          Pessoal que recolhemos é utilizado para fornecer e melhorar o Serviço.
          Nós iremos não utilize ou partilhe as suas informações com ninguém,
          excepto conforme descrito em esta Política de Privacidade.
        </p>
        <p>
          Os termos utilizados na presente Política de Privacidade têm os mesmos
          significados que nos nossos Termos e Condições, que são acessíveis na
          Conecta, salvo definição em contrário na presente Política de
          Privacidade.
        </p>
        <h2 className="font-bold py-4">Recolha e utilização da informação</h2>
        <p>
          Para uma melhor experiência, ao utilizar o nosso Serviço, podemos
          exigir-lhe que fornecer-nos certas informações pessoalmente
          identificáveis, incluindo mas não limitado a Nome, Endereços, Números
          de telefone,Pessoal número de identificação, Características pessoais,
          Data de nascimento, Geográfico localização, Dados de localização,
          Imagens, Câmara. As informações que solicitamos será retido por nós e
          utilizado como descrito nesta política de privacidade.
        </p>
        <div>
          <p>
            O aplicativo utiliza serviços de terceiros que podem recolher
            informações utilizado para o identificar.
          </p>
          <p>
            Link para a política de privacidade de prestadores de serviços de
            terceiros utilizados por o aplicativo
          </p>

          <div className="ml-10 mt-2">
            <ul className="list-disc">
              <li>
                <a
                  href="https://expo.io/privacy"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Expo
                </a>
              </li>
            </ul>
          </div>
        </div>
        <h2 className="font-bold py-4">Dados de registo</h2>
        <p>
          Queremos informar que sempre que utiliza o nosso Serviço, em caso de
          erro na aplicação, recolhemos dados e informações (através de produtos
          de terceiros) no seu telefone chamado Log Data. Estes Dados de Registo
          podem incluir informação como o seu endereço de Internet Protocol
          (&rdquo;IP&rdquo;) do dispositivo, dispositivo nome, versão do sistema
          operativo, a configuração da aplicação quando utilizando o nosso
          Serviço, a hora e a data da sua utilização do Serviço, e outras
          estatísticas.
        </p>

        <h2 className="font-bold py-4">Cookies</h2>

        <p>
          Os cookies são ficheiros com uma pequena quantidade de dados que são
          normalmente utilizados como identificadores únicos e anónimos. Estes
          são enviados para o seu navegador a partir do websites que visita e
          que são armazenados na memória interna dos seus dispositivos.
        </p>
        <p>
          Este Serviço não utiliza estes &rdquo;cookies&rdquo; explicitamente.
          No entanto, o aplicativo pode utilizar código de terceiros e
          bibliotecas que utilizam &rdquo;cookies&rdquo; para recolher
          informação e melhorar os seus serviços. Tem a opção de aceitar ou
          recusar estes cookies e saber quando um cookie está a ser enviado para
          o seu dispositivo. Se optar por recusar os nossos cookies, poderá não
          ser capaz de utilizar algumas porções deste Serviço.
        </p>

        <h2 className="font-bold py-4">Prestadores de serviços</h2>

        <p>
          Podemos empregar empresas e indivíduos de terceiros devido ao seguinte
          razões:
        </p>
        <div className="ml-10 mb-4 mt-2">
          <ul className="list-disc">
            <li>Para facilitar o nosso serviço;</li>
            <li>Para prestar o Serviço em nosso nome;</li>
            <li>To executar serviços relacionados com Serviços; ou</li>
            <li>
              Para nos ajudar na análise da forma como o nosso Serviço é
              utilizado.
            </li>
          </ul>
        </div>
        <p>
          Queremos informar os utilizadores deste Serviço que estes terceiros
          têm acesso à sua Informação Pessoal. A razão é executar as tarefas que
          lhes foi atribuído em nosso nome. No entanto, são obrigados a não
          divulgar ou utilizar a informação para qualquer outro fim.
        </p>

        <h2 className="font-bold py-4">Segurança</h2>

        <p>
          Valorizamos a sua confiança ao fornecer-nos os seus Dados Pessoais,
          por isso estão a esforçar-se por utilizar meios comercialmente
          aceitáveis para a proteger. Mas lembrar que nenhum método de
          transmissão através da Internet, ou método de o armazenamento
          electrónico é 100% seguro e fiável, e não podemos garantir a sua
          segurança absoluta.
        </p>
        <h2 className="font-bold py-4">Ligações para outros sites</h2>
        <p>
          Este Serviço pode conter links para outros sites. Se clicar num
          ligação de terceiros, será direccionado para esse sítio. Note-se que
          estes Os site externos não são operados por nós. Por conseguinte,
          aconselhamo-lo vivamente para rever a Política de Privacidade destes
          websites. Não temos qualquer controlo sobre e não assumir qualquer
          responsabilidade pelo conteúdo, políticas de privacidade, ou práticas
          de quaisquer sites ou serviços de terceiros.
        </p>

        <h2 className="font-bold py-4">Privacidade das crianças</h2>

        <div>
          <p>
            Estes Serviços não se dirigem a ninguém com idade inferior a 13
            anos. Não nos dirigimos recolher intencionalmente informações
            pessoalmente identificáveis de crianças com menos de 13 anos de
            idade. No caso de descobrirmos que uma criança com menos de 13
            forneceu-nos informações pessoais, apagamo-las imediatamente dos
            nossos servidores. Se é pai ou tutor e está ciente que o seu filho
            nos tenha fornecido informações pessoais, por favor contacte-nos
            para que possamos realizar as acções necessárias.
          </p>
        </div>
        <h2 className="font-bold py-4">
          Alterações a esta Política de Privacidade
        </h2>
        <p>
          Podemos actualizar a nossa Política de Privacidade de tempos a tempos.
          Assim, o senhor é aconselhado a rever esta página periodicamente para
          quaisquer alterações. Iremos notificar de quaisquer alterações,
          publicando a nova Política de Privacidade nesta página.
        </p>
        <p>Esta política é eficaz a partir de 2023-04-04</p>

        <h2 className="font-bold py-4">Contacte-nos</h2>

        <p>
          Se tiver quaisquer perguntas ou sugestões sobre a nossa Política de
          Privacidade, faça não hesite em contactar-nos em
          conectamobileapp@gmail.com.
        </p>
        <p>
          Esta página de política de privacidade foi criada em
          <a
            href="https://privacypolicytemplate.net"
            target="_blank"
            rel="noopener noreferrer"
          >
            privacypolicytemplate.net
          </a>
          e modificado/gerado por
          <a
            href="https://app-privacy-policy-generator.nisrulz.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Gerador da Política de Privacidade da App
          </a>
        </p>
      </main>
    </>
  );
};

export default Conecta;
